# Generated by Django 3.2.5 on 2021-07-03 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbrunch',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionbrunch',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='questionanswerforcontest',
            name='answer_index',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionanswerforcontest',
            name='answers',
            field=models.TextField(default='[]', null=True),
        ),
    ]
