# Generated by Django 3.2.5 on 2021-07-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0002_auto_20210704_0211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionbrunch',
            old_name='answer_index',
            new_name='option1',
        ),
        migrations.RenameField(
            model_name='questionbrunch',
            old_name='answers',
            new_name='option2',
        ),
        migrations.RemoveField(
            model_name='questionanswerforcontest',
            name='answer_index',
        ),
        migrations.RemoveField(
            model_name='questionanswerforcontest',
            name='answers',
        ),
        migrations.AddField(
            model_name='questionanswerforcontest',
            name='correct_answer_option',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='questionanswerforcontest',
            name='option1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionanswerforcontest',
            name='option2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionanswerforcontest',
            name='option3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionanswerforcontest',
            name='option4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionbrunch',
            name='correct_answer_option',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='questionbrunch',
            name='option3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionbrunch',
            name='option4',
            field=models.TextField(null=True),
        ),
    ]
