# Generated by Django 3.2.5 on 2021-07-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0003_auto_20210704_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='contesthistory',
            name='points',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
