# Generated by Django 3.2.5 on 2021-07-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0004_contesthistory_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=20, null=True),
        ),
    ]
