# Generated by Django 3.2.5 on 2021-07-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0005_contest_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlehistory',
            name='is_running',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
