# Generated by Django 3.2.5 on 2021-07-05 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0007_alter_userextendedprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlehistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
