# Generated by Django 3.2.5 on 2021-07-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0008_alter_battlehistory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlehistory',
            name='user1_answers',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='battlehistory',
            name='user2_answers',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='battlehistory',
            name='winner_user_id',
            field=models.TextField(default='', null=True),
        ),
    ]
