# Generated by Django 3.2.5 on 2021-07-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0009_auto_20210705_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextendedprofile',
            name='profileimage',
            field=models.TextField(default='default/profileavatar.jpg', null=True),
        ),
    ]
