# Generated by Django 3.2.5 on 2021-07-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0010_userextendedprofile_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='point_to_deduct',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
