# Generated by Django 3.2.5 on 2021-07-09 15:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0013_contesthistory_is_running'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contesthistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
