# Generated by Django 3.2.5 on 2021-07-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0016_contesthistory_result_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='contesthistory',
            name='percentagee_of_correct_answers',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
