# Generated by Django 3.2.5 on 2021-07-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0017_contesthistory_percentagee_of_correct_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contesthistory',
            old_name='percentagee_of_correct_answers',
            new_name='percentage_of_correct_answers',
        ),
    ]
