# Generated by Django 3.2.5 on 2021-07-09 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0019_contesthistory_is_evalauted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contesthistory',
            old_name='is_evalauted',
            new_name='is_evaluated',
        ),
    ]
