# Generated by Django 3.2.5 on 2021-07-09 22:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0020_rename_is_evalauted_contesthistory_is_evaluated'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPackages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coins', models.IntegerField(default=0, null=True)),
                ('price', models.IntegerField(default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
