# Generated by Django 3.2.5 on 2021-07-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0022_transactionlogs_coins_to_be_deposited'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextendedprofile',
            name='score_contest',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
