# Generated by Django 3.2.5 on 2021-07-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0023_userextendedprofile_score_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextendedprofile',
            name='score_contest',
            field=models.FloatField(default=0, null=True),
        ),
    ]
